import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import bannerImage from '../public/images/road.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={'h-[400px] relative flex items-center justify-center'}>
          <Image className={'absolute top-0 left-0 object-cover w-full h-full'} src={bannerImage} alt={'Road'}/>
          <div className={'bg-white rounded shadow p-4 z-10'}>
            Let Us Help Your On Your Journey
          </div>
        </div>
        <div className={'flex'}>
          <div className={'flex-1 m-4 p-4 shadow-lg rounded border border-gray-200'}>
            <h1 className={'text-center text-xl '}>Schedule A Move</h1>
          </div>
          <div className={'flex-1 m-4 p-4 shadow-lg rounded border border-gray-200'}>
            <h1 className={'text-center text-xl'}>Rent a Vehicle</h1>
          </div>
        </div>
      </main>
    </>
  )
}
